var mongoose = require('mongoose')
var certificationSchema = new mongoose.Schema({
    tubeId:{
        type:mongoose.Schema.Types.ObjectId,
        required:true
    },
    tubeName:{
        type:String,
        required:true
    },
    thumbnail:{
            type:String,
            required:true
    },
    learnerId:{
        type:mongoose.Schema.Types.ObjectId,
        required:true
    },
    learnerName:{
        type:String,
        required:true
    },
   
    language:{
        type:String,
        required:true
    },
 
    youtuberName:{
        type:String,
        required:true
    },
    youtuberChannelName:{
        type:String,
        required:true
    },
    scoredAtQuiz:{
        type:Number,
        required:true
    },
    totalQuizPoints:{
        type:Number,
        default:15
    },
    scoredOnAiEvaluationAtProject:{
type:Number,
required:true
    },
    totalSoredOnAiEvaluationAtProjectPoints:{
        type:Number,
        default:15
    },
    git_fullName:{
        type:String,
        required:true
    },
 
    git_name:{
            type:String,
            required:true
    },
    git_url:{
        type:String,
        required:true
    },
    git_description:{
        type:String,
    },
    git_language:{
        type:String,
        required:true
    },
    git_stars:{
        type:Number
    },
    git_forks:{
        type:Number
    },
    git_pushed_at:{
        type:Date,
        required:true
    },
    git_visibility:{
        type:String,
        required:true
    },
    isMinted:{
        type:Boolean,
        default:false
    },
    issuedDate:{
        type:Date,
        
    },
  
})
module.exports = mongoose.model("CertificationSchema",certificationSchema)